const $=id=>document.getElementById(id),secs={deutsch:"Deutschverständnis",konzentration:"Konzentration",aufmerksamkeit:"Aufmerksamkeit",orientierung:"Orientierung",logik:"Logik / Arbeitsgedächtnis",belastbarkeit:"Belastbarkeit",reaktion:"Reaktion"};
const modes={learn:{id:"learn",label:"Lernmodus",bp:["de","sym","grid","line","num","mem","rule","cmp","react","nogo"]},short:{id:"short",label:"Prüfungsmodus kurz",bp:["de","de","sym","sym","cmp","grid","line","line","num","mem","mem","rule","rule","route","react","nogo","stress","att"]},long:{id:"long",label:"Prüfungsmodus lang",bp:["de","de","de","sym","sym","sym","cmp","cmp","att","att","grid","grid","route","line","line","line","num","num","num","mem","mem","mem","rule","rule","rule","stress","stress","react","nogo","nogo","sym","grid","cmp","de","mem","line"]}};
const dePool=[
["Anweisung genau lesen","Sie sehen ein rotes Licht. Sie dürfen erst drücken, wenn das Licht grün wird. Was ist richtig?",["Ich drücke sofort bei Rot.","Ich warte auf Grün und drücke dann.","Ich drücke, wenn ich unsicher bin.","Ich drücke gar nicht."],1,"ترى ضوءاً أحمر. لا يجوز الضغط إلا عندما يصبح الضوء أخضر."],
["Ruhig bleiben","Ein Fahrgast fragt unfreundlich nach dem Weg. Was ist die beste Reaktion?",["Ich antworte ruhig und kurz.","Ich werde laut.","Ich ignoriere ihn immer.","Ich verlasse den Bus sofort."],0,"راكب يسأل بطريقة غير لطيفة. الأفضل أن تجيب بهدوء."],
["Termin vorbereiten","Am Prüfungstag sollst du ausgeruht und rechtzeitig erscheinen. Was machst du?",["Ich komme knapp.","Ich schlafe wenig.","Ich plane die Fahrt vorher und komme rechtzeitig.","Ich übe nur Arabisch."],2,"في يوم الفحص يجب أن تصل في الوقت المناسب وأن تكون مرتاحاً."],
["Doppelte Bedingung","Klicken Sie nur, wenn das Feld GRÜN ist und das Wort BUS zeigt. Was ist richtig?",["GRÜN + BUS","GRÜN + PKW","ROT + BUS","BLAU + BUS"],0,"اضغط فقط إذا كان الحقل أخضر وتظهر كلمة BUS."],
["Sicheres Verhalten","Während einer Aufgabe wirst du unsicher. Was ist sinnvoll?",["Ich klicke hektisch.","Ich lese die Regel ruhig noch einmal.","Ich öffne Arabisch und erwarte Punkte.","Ich beende alles."],1,"إذا كنت غير متأكد، اقرأ القاعدة بهدوء مرة أخرى."]];
const rules=[
["Mehrere Regeln","Regel: Bei Kreis wähle JA. Bei Quadrat wähle NEIN. Bei DREIECK wähle JA.","Was wählst du bei: DREIECK?",["JA","NEIN","Warten","Überspringen"],0,"عند DREIECK اختر نعم."],
["Regelwechsel","Neue Regel: JA nur, wenn die Zahl gerade ist und das Wort BUS daneben steht.","Was wählst du bei: 8 BUS?",["JA","NEIN","Nur wenn grün","Nicht antworten"],0,"اختر نعم فقط إذا كان الرقم زوجياً وكانت الكلمة BUS."],
["Fehlerkontrolle","Bei Belastung ist wichtig: ruhig und genau arbeiten.","Du merkst einen Fehler. Was ist sinnvoll?",["Hektisch schneller klicken.","Ruhig bleiben und weitermachen.","Alles abbrechen.","Arabisch öffnen, damit es Punkte gibt."],1,"عند الخطأ: ابق هادئاً وتابع."]];
const lineTpl=[{ask:1,cor:"D",p:["M80 55 C220 25 260 180 470 245 L565 255","M80 120 C210 120 300 40 565 70","M80 185 C220 245 310 80 565 175","M80 250 C210 210 340 270 565 115"]},{ask:3,cor:"B",p:["M80 60 C240 100 285 220 565 250","M80 125 C250 35 350 70 565 65","M80 190 C260 260 310 110 565 125","M80 250 C220 150 350 210 565 185"]},{ask:4,cor:"A",p:["M80 55 C190 90 330 30 565 180","M80 120 C260 230 340 265 565 245","M80 185 C220 155 370 160 565 120","M80 250 C235 200 300 60 565 60"]},{ask:2,cor:"C",p:["M80 58 C250 28 345 95 565 122","M80 122 C220 250 370 210 565 184","M80 188 C240 155 320 65 565 62","M80 250 C245 230 330 275 565 250"]}];
let st={mode:null,plan:[],i:0,ans:null,set:new Set(),ar:false,earned:0,total:0,arCount:0,details:{},start:0,timer:null,last:null,rt:null};
const pick=a=>a[Math.floor(Math.random()*a.length)],rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,sh=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a},esc=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c])),dur=s=>`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`,fp=n=>Number.isInteger(n)?n:String(n.toFixed(1));
function initD(){st.details={};Object.values(secs).forEach(x=>st.details[x]={earned:0,total:0,arabic:0,tasks:0,correct:0})}
function start(id){st={...st,mode:modes[id]||modes.short,plan:[],i:0,ans:null,set:new Set(),ar:false,earned:0,total:0,arCount:0,start:Date.now(),last:null,rt:null};initD();st.plan=st.mode.bp.map(make);tick();st.timer=setInterval(tick,1e3);render()}
function make(k){let f={de:mkDe,sym:mkSym,grid:mkGrid,line:mkLine,num:mkNum,mem:mkMem,rule:mkRule,cmp:mkCmp,react:()=>mkReact("simple"),nogo:()=>mkReact("nogo"),stress:mkStress,route:mkRoute,att:mkAtt}[k];return f()}
function choice(sec,title,inst,q,opt,cor,ar,w=1){return{type:"choice",sec,title,inst,q,opt:opt.map(x=>({de:x,ar:x})),cor,ar,w}}
function mkDe(){let x=pick(dePool);return choice("deutsch",x[0],"Lies die deutsche Anweisung genau und wähle die richtige Antwort.",x[1],x[2],x[3],x[4],1)}
function mkRule(){let x=pick(rules);return choice("belastbarkeit",x[0],x[1],x[2],x[3],x[4],x[5],1.2)}
function mkStress(){let n=rand(1,9),w=pick(["BUS","PKW","HALT","LINIE"]),c=n%2===0&&w==="BUS"?0:1;return choice("belastbarkeit","Belastbarkeit mit Regel","Regel: JA nur, wenn die Zahl gerade ist und das Wort BUS lautet. Sonst NEIN.",`Was wählst du bei: ${n} ${w}?`,["JA","NEIN","Überspringen","Warten"],c,"اختر نعم فقط إذا كان الرقم زوجياً وكانت الكلمة BUS.",1.2)}
function mkNum(){let t=pick(["d","p","m"]),seq,c;if(t==="d"){let a=pick([2,3,4]);seq=[a,a*2,a*4,a*8];c=a*16}else if(t==="p"){let a=rand(2,8),s=rand(3,7);seq=[a,a+s,a+2*s,a+3*s];c=a+4*s}else{let a=rand(32,55),s=rand(4,9);seq=[a,a-s,a-2*s,a-3*s];c=a-4*s}let o=sh([c,c+rand(2,6),Math.max(0,c-rand(2,6)),c+rand(7,13)]).map(String);return choice("logik","Zahlenreihe","Setze die Reihe fort. Arbeite ruhig und prüfe das Muster.",`${seq.join(" – ")} – ?`,o,o.indexOf(String(c)),"أكمل السلسلة بهدوء.",1)}
function mkMem(){let a=sh(["🚌","▲","●","■","◆","→","★","☐"]).slice(0,rand(4,5)),c=a.join("  "),o=sh([c,sh(a).join("  "),[...a].reverse().join("  "),a.map((x,i)=>i===1?"○":x).join("  ")]).filter((x,i,b)=>b.indexOf(x)===i);return{type:"mem",sec:"logik",title:"Arbeitsgedächtnis",inst:"Merke dir die Reihenfolge. Nach kurzer Zeit verschwindet sie.",ar:"احفظ الترتيب ثم اختر الترتيب الصحيح.",seq:c,opt:o.map(x=>({de:x,ar:x})),cor:o.indexOf(c),w:1.4}}
function mkSym(){let v=pick([{target:"d''",pool:["d'","p''","d''","d'''","p'","p'''","d''''"],inst:"Klicke nur auf jedes d mit genau zwei Strichen.",ar:"اضغط فقط على d مع خطين."},{target:"P•",pool:["P•","•P","B•","P:",":P","•B"],inst:"Klicke nur auf jedes P mit Punkt rechts: P•.",ar:"اضغط فقط على P مع نقطة في اليمين."},{target:"⚑",pool:["⚐","⚑","◇","△","○","□"],inst:"Klicke alle Felder mit ⚑ an.",ar:"اضغط على كل خانات ⚑."}]),items=[],cor=[];for(let i=0;i<40;i++){let tg=Math.random()<.22&&cor.length<10,s=tg?v.target:pick(v.pool.filter(x=>x!==v.target));if(s===v.target)cor.push(i);items.push(s)}while(cor.length<7){let i=rand(0,39);if(!cor.includes(i)){items[i]=v.target;cor.push(i)}}return{type:"multi",sec:"konzentration",title:"Symbolsuche",inst:v.inst,ar:v.ar,target:v.target,items,cor:cor.sort((a,b)=>a-b),w:2}}
function mkAtt(){let target="BUS7",pool=["BUS1","BÜS7","8US7","BUSI","PUS7","BUS?","BU57"],items=Array.from({length:36},()=>pick(pool)),cor=[];while(cor.length<rand(5,8)){let i=rand(0,35);if(!cor.includes(i)){items[i]=target;cor.push(i)}}return{type:"multi",sec:"aufmerksamkeit",title:"Aufmerksamkeit bei ähnlichen Zeichen",inst:"Klicke nur auf BUS7. Ähnliche Zeichen sind falsch.",ar:"اضغط فقط على BUS7.",target,items,cor:cor.sort((a,b)=>a-b),w:2}}
function mkCmp(){let p=pick([["7429","7429",1],["6138","6183",0],["B-17","B-17",1],["D-41","D-14",0],["LINIE 5","LINIE 5",1],["HALT 8","HALT B",0]]);return choice("aufmerksamkeit","Vergleichen","Prüfe genau: Sind beide Zeichenfolgen gleich?",`${p[0]}    |    ${p[1]}`,["Gleich","Nicht gleich","Nicht sicher","Überspringen"],p[2]?0:1,"هل السلسلتان متطابقتان؟",1)}
function mkGrid(){let cols=5,rows=5,l=[];for(let y=1;y<=rows;y++)for(let x=0;x<cols;x++)l.push(`${String.fromCharCode(65+x)}${y}`);let x=rand(0,4),y=rand(0,4),sx=x,sy=y,dirs=[{dx:1,dy:0,de:"rechts",ar:"يمين"},{dx:-1,dy:0,de:"links",ar:"يسار"},{dx:0,dy:1,de:"unten",ar:"أسفل"},{dx:0,dy:-1,de:"oben",ar:"أعلى"}],steps=[];for(let i=0;i<4;i++){let ps=dirs.filter(d=>x+d.dx>=0&&x+d.dx<cols&&y+d.dy>=0&&y+d.dy<rows),d=pick(ps);x+=d.dx;y+=d.dy;steps.push(d)}let s=`${String.fromCharCode(65+sx)}${sy+1}`,e=`${String.fromCharCode(65+x)}${y+1}`;return{type:"grid",sec:"orientierung",title:"Orientierung im Raster",inst:`Start ist ${s}. Gehe: ${steps.map(z=>`1 Feld nach ${z.de}`).join(", ")}. Wo bist du?`,ar:`البداية ${s}. تحرك حسب التعليمات واختر النهاية.`,items:l,cols,start:l.indexOf(s),cor:[l.indexOf(e)],w:1.5}}
function mkRoute(){let stp=["A","B","C","D","E","F","G","H","I"],si=rand(0,4),m=[rand(1,2),rand(1,2),rand(1,2)],ei=Math.min(8,si+m.reduce((a,b)=>a+b,0)),c=stp[ei],o=sh([c,stp[Math.max(0,ei-1)],stp[Math.min(8,ei+1)],stp[rand(0,8)]]).filter((v,i,a)=>a.indexOf(v)===i);while(o.length<4)o.push(pick(stp.filter(s=>!o.includes(s))));return choice("orientierung","Busroute","Zähle die Haltestellen auf der Linie.",`Start an Haltestelle ${stp[si]}. Fahre ${m[0]}, dann ${m[1]}, dann ${m[2]} Haltestelle(n) weiter. Wo bist du?`,o.map(x=>`Haltestelle ${x}`),o.indexOf(c),"عدّ المحطات واختر محطة الوصول.",1.2)}
function mkLine(){let t=pick(lineTpl);return{type:"line",sec:"orientierung",title:"Linien verfolgen",inst:`Folge in der Grafik Linie ${t.ask}. Welcher Zielbuchstabe gehört zu dieser Linie?`,ar:`اتبع الخط رقم ${t.ask} واختر حرف النهاية.`,tpl:t,opt:["Ziel A","Ziel B","Ziel C","Ziel D"].map(x=>({de:x,ar:x})),cor:["A","B","C","D"].indexOf(t.cor),w:1.7}}
function mkReact(kind){return{type:"reaction",sec:"reaktion",title:kind==="simple"?"Einfache Reaktion":"Go / No-Go Reaktion",inst:kind==="simple"?"Drücke so schnell wie möglich, wenn GRÜN erscheint. Drücke nicht vorher.":"Drücke nur bei GRÜN + BUS. Bei allen anderen Signalen nicht drücken.",ar:kind==="simple"?"اضغط عندما يظهر الأخضر فقط.":"اضغط فقط عند أخضر + BUS.",kind,rounds:kind==="simple"?8:12,out:null,w:kind==="simple"?2:2.5}}
function show(id){["introCard","testCard","resultsCard","historyCard"].forEach(x=>$(x).classList.add("hidden"));$(id).classList.remove("hidden")}
function render(){if(st.i>=st.plan.length)return finish();show("testCard");let t=st.plan[st.i];st.ans=null;st.set=new Set;st.ar=false;st.rt=null;$("sectionLabel").textContent=secs[t.sec];$("taskTitle").textContent=t.title;$("taskInstruction").textContent=t.inst;$("stepNow").textContent=st.i+1;$("stepTotal").textContent=st.plan.length;$("barFill").style.width=`${Math.round(st.i/st.plan.length*100)}%`;$("modeLabel").textContent=st.mode.label;$("scoreLiveLabel").textContent=`${fp(st.earned)} / ${fp(st.total)} Punkte`;$("arabicBox").classList.add("hidden");$("arabicBox").innerHTML="";$("arabicBtn").disabled=false;$("arabicBtn").textContent="Arabisch anzeigen – diese Aufgabe gibt dann 0 Punkte";$("feedbackBox").className="feedback hidden";$("nextBtn").disabled=true;$("skipBtn").disabled=false;$("taskBody").innerHTML="";({choice:rChoice,multi:rMulti,grid:rGrid,line:rLine,mem:rMem,reaction:rReact}[t.type])(t);scrollTo({top:0,behavior:"smooth"})}
function rChoice(t){let b=$("taskBody"),q=document.createElement("div");q.className="questionBox";q.innerHTML=`<strong>Frage:</strong><br>${esc(t.q)}`;b.append(q);opts(t.opt,(i,btn,box)=>{st.ans=i;[...box.children].forEach(x=>x.classList.remove("selected"));btn.classList.add("selected");$("nextBtn").disabled=false})}
function opts(o,fn){let box=document.createElement("div");box.className="options";o.forEach((x,i)=>{let btn=document.createElement("button");btn.type="button";btn.className="option";btn.textContent=x.de||x;btn.onclick=()=>fn(i,btn,box);box.append(btn)});$("taskBody").append(box)}
function rMulti(t){let b=$("taskBody"),q=document.createElement("div");q.className="questionBox";q.innerHTML=`<strong>Zielzeichen:</strong> ${esc(t.target)}<br>Es sind mehrere Felder richtig.`;b.append(q);let g=document.createElement("div");g.className="symbolGrid";t.items.forEach((s,i)=>{let c=document.createElement("button");c.type="button";c.className="symbol";c.textContent=s;c.onclick=()=>{st.set.has(i)?(st.set.delete(i),c.classList.remove("selected")):(st.set.add(i),c.classList.add("selected"));$("nextBtn").disabled=st.set.size===0};g.append(c)});b.append(g)}
function rGrid(t){let g=document.createElement("div");g.className="matrix";g.style.setProperty("--cols",t.cols||5);g.style.setProperty("--cols-mobile",Math.min(t.cols||5,3));t.items.forEach((it,i)=>{let b=document.createElement("button");b.type="button";b.textContent=it;if(i===t.start)b.classList.add("routeStart");b.onclick=()=>{st.set=new Set([i]);[...g.children].forEach(x=>x.classList.remove("selected"));b.classList.add("selected");$("nextBtn").disabled=false};g.append(b)});$("taskBody").append(g)}
function rLine(t){let yS={1:55,2:120,3:185,4:250},yE={A:60,B:120,C:180,D:250},p=t.tpl.p.map((d,i)=>`<path class="linePath ${i%2?"alt":""}" d="${d}"/>`).join(""),s=[1,2,3,4].map(n=>`<circle class="lineDot" cx="58" cy="${yS[n]}" r="17"/><text class="lineLabel" x="53" y="${yS[n]+6}">${n}</text>`).join(""),e=["A","B","C","D"].map(l=>`<circle class="lineDot" cx="590" cy="${yE[l]}" r="18"/><text class="lineLabel" x="584" y="${yE[l]+6}">${l}</text>`).join("");let pan=document.createElement("div");pan.className="visualPanel";pan.innerHTML=`<svg class="lineSvg" viewBox="0 0 650 320"><rect width="650" height="320" rx="18" fill="#f8fafc"/><text class="lineLabel" x="28" y="26">Start</text><text class="lineLabel" x="557" y="26">Ziel</text>${p}${s}${e}</svg>`;$("taskBody").append(pan);opts(t.opt,(i,btn,box)=>{st.ans=i;[...box.children].forEach(x=>x.classList.remove("selected"));btn.classList.add("selected");$("nextBtn").disabled=false})}
function rMem(t){let box=document.createElement("div");box.className="memoryBox";box.innerHTML=`<div class="countdown">Merken: 4 Sekunden</div><div class="memorySequence">${esc(t.seq)}</div>`;$("taskBody").append(box);let l=4,tm=setInterval(()=>{if(--l>0)box.querySelector(".countdown").textContent=`Merken: ${l} Sekunden`;else{clearInterval(tm);box.innerHTML=`<div class="countdown">Welche Reihenfolge war richtig?</div>`;opts(t.opt,(i,btn,op)=>{st.ans=i;[...op.children].forEach(x=>x.classList.remove("selected"));btn.classList.add("selected");$("nextBtn").disabled=false})}},1e3)}
function rReact(t){$("taskBody").innerHTML=`<div class="reactionStage" id="reactionStage"><div class="signal wait" id="signalBox">Start drücken</div></div><div class="reactionStats" id="reactionStats">Bereit. Leertaste oder Enter gehen auch.</div><div class="taskFooter"><button class="primary" id="reactionStartBtn" type="button">Reaktionsaufgabe starten</button></div>`;st.rt={t,round:0,res:[],timer:null,go:null,target:false,answered:false,running:false};$("reactionStartBtn").onclick=beginR;$("reactionStage").onclick=hitR}
function beginR(){let r=st.rt;if(!r||r.running)return;r.running=true;$("reactionStartBtn").disabled=true;nextR()}
function nextR(){let r=st.rt;if(!r)return;clearTimeout(r.timer);if(r.round>=r.t.rounds)return doneR();r.answered=false;r.go=null;$("signalBox").className="signal wait";$("signalBox").textContent="Warten…";r.timer=setTimeout(()=>{r.round++;let v=r.t.kind==="simple"?{text:"GRÜN\nKLICKEN",target:true}:pick([{text:"GRÜN\nBUS",target:true},{text:"GRÜN\nPKW",target:false},{text:"ROT\nBUS",target:false},{text:"GRAU\nBUS",target:false}]);r.target=v.target;r.go=performance.now();$("signalBox").className=`signal ${v.target?"go":"no"}`;$("signalBox").textContent=v.text;r.timer=setTimeout(()=>{if(!r.answered){r.res.push({target:v.target,hit:false,falseAlarm:false,correctNoGo:!v.target,rt:null});statR()}nextR()},v.target?1650:900)},rand(800,2100))}
function hitR(){let r=st.rt;if(!r||!r.running||r.go===null||r.answered)return;r.answered=true;let ms=Math.round(performance.now()-r.go);r.res.push({target:r.target,hit:r.target,falseAlarm:!r.target,correctNoGo:false,rt:r.target?ms:null});clearTimeout(r.timer);statR();setTimeout(nextR,280)}
function statR(){let r=st.rt,h=r.res.filter(x=>x.hit).length,f=r.res.filter(x=>x.falseAlarm).length,n=r.res.filter(x=>x.correctNoGo).length,rt=r.res.filter(x=>x.rt).map(x=>x.rt),avg=rt.length?Math.round(rt.reduce((a,b)=>a+b,0)/rt.length):"–";$("reactionStats").textContent=`Runde ${Math.min(r.round,r.t.rounds)} / ${r.t.rounds} · Treffer: ${h} · richtig nicht gedrückt: ${n} · Fehlklicks: ${f} · Ø ${avg} ms`}
function doneR(){let r=st.rt,tar=r.res.filter(x=>x.target).length,h=r.res.filter(x=>x.hit).length,f=r.res.filter(x=>x.falseAlarm).length,n=r.res.filter(x=>x.correctNoGo).length,non=r.res.filter(x=>!x.target).length,rt=r.res.filter(x=>x.rt).map(x=>x.rt),avg=rt.length?Math.round(rt.reduce((a,b)=>a+b,0)/rt.length):null,acc=(tar?h/tar:1)*.55+(non?n/non:1)*.35+(f===0?.1:f===1?.04:0),spd=avg===null?.7:avg<=800?1:avg<=1100?.75:avg<=1400?.45:.2;r.t.out={ratio:Math.max(0,Math.min(1,acc*.78+spd*.22)),avg,h,f,n,tar,non};$("signalBox").className="signal wait";$("signalBox").textContent="Fertig";$("reactionStats").textContent=`Fertig · Treffer: ${h}/${tar||0} · Fehlklicks: ${f} · Ø ${avg||"–"} ms`;$("nextBtn").disabled=false}
function showAr(){let t=st.plan[st.i];st.ar=true;$("arabicBox").classList.remove("hidden");$("arabicBox").innerHTML=`<strong>مساعدة عربية:</strong><br>${esc(t.ar||"اقرأ التعليمات الألمانية جيداً.")}${t.opt?"<ol>"+t.opt.map(o=>`<li>${esc(o.ar||o.de)}</li>`).join("")+"</ol>":""}`;$("arabicBtn").textContent="Arabisch wurde geöffnet – 0 Punkte für diese Aufgabe";$("arabicBtn").disabled=true}
function same(a,b){if(a.size!==b.size)return false;for(let x of a)if(!b.has(x))return false;return true}
function partial(a,b){if(!a.size)return 0;let h=0,f=0;for(let x of a)b.has(x)?h++:f++;let m=b.size-h;return Math.max(0,Math.min(.8,h/b.size-f*.18-m*.08))}
function grade(skip=false){let t=st.plan[st.i],sec=secs[t.sec],w=t.w||1,ratio=0,cor=false;if(!skip&&!st.ar){if(["choice","line","mem"].includes(t.type)){cor=st.ans===t.cor;ratio=cor?1:0}else if(["multi","grid"].includes(t.type)){cor=same(st.set,new Set(t.cor));ratio=cor?1:partial(st.set,new Set(t.cor))}else if(t.type==="reaction"){ratio=t.out?t.out.ratio:0;cor=ratio>=.75}}if(st.ar){st.arCount++;st.details[sec].arabic++}let e=st.ar?0:Math.round(w*ratio*10)/10;st.total+=w;st.earned+=e;st.details[sec].total+=w;st.details[sec].earned+=e;st.details[sec].tasks++;if(cor)st.details[sec].correct++;st.i++;render()}
function finish(){clearInterval(st.timer);let elapsed=Math.round((Date.now()-st.start)/1e3),pct=st.total?Math.round(st.earned/st.total*100):0,a={date:new Date().toISOString(),mode:st.mode.id,modeLabel:st.mode.label,earned:Math.round(st.earned*10)/10,total:Math.round(st.total*10)/10,percent:pct,arabicPenaltyCount:st.arCount,elapsedSec:elapsed,details:st.details};st.last=a;save(a);res(a)}
function res(a){show("resultsCard");$("resultModeLabel").textContent=`${a.modeLabel} · ${dur(a.elapsedSec)}`;$("scorePercent").textContent=`${a.percent}%`;$("scoreCircle").style.background=`conic-gradient(var(--accent) 0deg,var(--accent) ${a.percent*3.6}deg,#e9eef8 ${a.percent*3.6}deg)`;$("scoreTitle").textContent=a.percent>=82&&a.arabicPenaltyCount===0?"Starkes Übungsergebnis":a.percent>=68?"Solide Grundlage":"Weiter üben";$("scoreText").textContent=a.percent>=68?"Ziel: mehrere Durchgänge stabil und möglichst ohne arabische Hilfe schaffen.":"Wichtig sind ruhiges Lesen, genaues Arbeiten und Reaktion ohne Fehlklicks.";$("badgeRow").innerHTML=[a.arabicPenaltyCount===0?"Deutsch ohne Hilfe":"",a.percent>=75?"stabiler Durchgang":"",a.elapsedSec>1200?"Ausdauer geübt":""].filter(Boolean).map(x=>`<span class="resultBadge">${x}</span>`).join("");let box=$("sectionResults");box.innerHTML="";Object.entries(a.details).forEach(([n,d])=>{if(!d.total)return;let p=Math.round(d.earned/d.total*100),div=document.createElement("div");div.className="resultBox";div.innerHTML=`<strong>${esc(n)}</strong><div>${p}% · ${fp(d.earned)} von ${fp(d.total)} Punkten</div><div class="miniBar"><span style="width:${p}%"></span></div><small>${d.tasks} Aufgabe(n)${d.arabic?` · Arabisch: ${d.arabic}×`:""}</small>`;box.append(div)});$("arabicNotice").innerHTML=a.arabicPenaltyCount?`<strong>Arabische Hilfe genutzt:</strong> ${a.arabicPenaltyCount} Aufgabe(n) wurden dadurch mit 0 Punkten bewertet. Gleichen Modus anschließend ohne Arabisch wiederholen.`:`<strong>Sehr gut:</strong> Keine arabische Hilfe genutzt.`}
function save(a){let x=get();x.push(a);localStorage.setItem("busEignungTrainingAttemptsV2",JSON.stringify(x.slice(-60)))}function get(){try{return JSON.parse(localStorage.getItem("busEignungTrainingAttemptsV2")||"[]")}catch{return[]}}
function hist(){show("historyCard");clearInterval(st.timer);let a=get(),b=$("historyBody");if(!a.length){b.innerHTML='<div class="notice">Noch kein gespeicherter Test.</div>';return}let best=Math.max(...a.map(x=>x.percent)),cur=a.at(-1).percent,first=a[0].percent,noAr=a.filter(x=>x.arabicPenaltyCount===0).length,bars=a.slice(-10).map(x=>`<div class="historyBar"><span>${new Date(x.date).toLocaleDateString("de-DE",{day:"2-digit",month:"2-digit"})}</span><div class="historyBarLine"><div class="historyBarFill" style="width:${x.percent}%"></div></div><strong>${x.percent}%</strong></div>`).join(""),rows=a.slice().reverse().map(x=>`<tr><td>${new Date(x.date).toLocaleString("de-DE",{dateStyle:"short",timeStyle:"short"})}</td><td>${esc(x.modeLabel||x.mode)}</td><td>${x.percent}%</td><td>${fp(x.earned)} / ${fp(x.total)}</td><td>${x.arabicPenaltyCount}</td><td>${dur(x.elapsedSec||0)}</td></tr>`).join("");b.innerHTML=`<div class="grid two"><div class="resultBox"><strong>Bester Durchgang</strong>${best}%</div><div class="resultBox"><strong>Entwicklung seit erstem Test</strong>${cur-first>=0?"+":""}${cur-first} Prozentpunkte</div><div class="resultBox"><strong>Durchgänge ohne Arabisch</strong>${noAr} von ${a.length}</div><div class="resultBox"><strong>Empfehlung</strong>${a.at(-1).arabicPenaltyCount?"Gleichen Modus ohne Arabisch wiederholen.":a.at(-1).percent<65?"Lernmodus nutzen.":"Regelmäßig kurz üben."}</div></div><h3>Letzte Durchgänge</h3><div class="historyBars">${bars}</div><h3>Alle gespeicherten Versuche</h3><table class="historyTable"><thead><tr><th>Datum</th><th>Modus</th><th>Score</th><th>Punkte</th><th>Arabisch</th><th>Dauer</th></tr></thead><tbody>${rows}</tbody></table>`}
function tick(){if(st.start)$("elapsedLabel").textContent=dur(Math.round((Date.now()-st.start)/1e3))}
$("quickStartBtn").onclick=()=>start("short");$("historyTopBtn").onclick=hist;$("showHistoryBtn").onclick=hist;$("chooseModeBtn").onclick=()=>show("introCard");$("repeatModeBtn").onclick=()=>start(st.mode?.id||"short");$("backBtn").onclick=()=>show(st.last?"resultsCard":"introCard");$("clearHistoryBtn").onclick=()=>{if(confirm("Verlauf wirklich löschen?")){localStorage.removeItem("busEignungTrainingAttemptsV2");hist()}};$("arabicBtn").onclick=showAr;$("nextBtn").onclick=()=>grade(false);$("skipBtn").onclick=()=>grade(true);document.querySelectorAll(".modeCard").forEach(b=>b.onclick=()=>start(b.dataset.mode));document.addEventListener("keydown",e=>{if(!$("testCard").classList.contains("hidden")&&(e.code==="Space"||e.code==="Enter")&&st.plan[st.i]?.type==="reaction"){e.preventDefault();hitR()}});
